### ISSUE TITLE
A11y - W3C, H64: Using the title attribute of the frame and iframe elements

### ISSUE THREAD

**Issue by ioanna0** [seatsio/seatsio-react#104]
Hi, 

Looking to add a title attribute to the seats.io generated iframe as per the https://www.w3.org/TR/WCAG20-TECHS/H64.html 
Is there a way to add one programmatically? Or would be nice if you could add a default one with option to override.

Many Thanks

**Comment by bverbeken** [comment]
Hi, 

We'll consider adding a title attribute to the generated iframe. However, we don't plan to make that iframe title configurable/overridable: the mere existence of the iframe is actually an implementation detail, and so public API to change iframe attributes would not make much sense. 

Closing this issue here as this is not directly related to the seatsio-react client library, but rather any seats.io seating chart. For further support questions, please reach out to support@seats.io.
